### PR TITLE
Bugfix/UI bug double borders around photo grid

### PR DESCRIPTION
**Pull request by 0xRowdy**
Fixed UI bugs around the grids showing double borders. Added Animation to the booth footer

## Description

Refactored the booth display to use a table. This allows for the use of border-collapse to prevent double border of images. Fixed extra borders that were appearing on the Artboard.

## Related Issue

[Issue 43](https://github.com/semaphore-protocol/taz-apps/issues/43)

## Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

## Other information

Booth Display
Screen Shot 2022-10-04 at 11 00 23 AM

Artboard Drawing Grid
Screen Shot 2022-10-04 at 8 46 14 AM

Animation

https://user-images.githubusercontent.com/22626267/193887031-f8bbba09-bf3d-4b74-b58b-9fae22a62830.mov

### CODE REVIEW

**Review by CJ-Rose — CHANGES_REQUESTED** [review]
Mark can we merge this to dev first?

**Review by CJ-Rose — APPROVED** [review]

**Review by cedoor — APPROVED** [review]

**Comment by cedoor** [comment]
@0xRowdy 

There are some conflicts. Maybe you should pull some changes from `dev`.

**Comment by 0xRowdy** [comment]
> @0xRowdy
> 
> There are some conflicts. Maybe you should pull some changes from `dev`.

No problem. I'm always getting conflicts around the sw.js.map. Is that something that should be ignored or should I include it in every commit?

**Comment by cedoor** [comment]
> > @0xRowdy
> > There are some conflicts. Maybe you should pull some changes from `dev`.
> 
> No problem. I'm always getting conflicts around the sw.js.map. Is that something that should be ignored or should I include it in every commit?

I searched for it and it looks like a file generated by [`next-pwa`](https://github.com/shadowwalker/next-pwa#step-1-withpwa), which shouldn't be ignored :/

**Comment by 0xRowdy** [comment]
> 

Ahh gosh sorry. I've added appropriate files to the gitignore.

**Comment by cedoor** [comment]
> Ahh gosh sorry. I've added appropriate files to the gitignore.

Well, I'm not sure but I feel like they shouldn't be ignored

**Pull request merged**
